[package]
name = "wyrm"
version = "0.9.1"
authors = ["Maciej Kula"]
license = "MIT"
description = "A low-overhead, define-by-run autodifferentiation library."
documentation = "https://docs.rs/wyrm/"
repository = "https://github.com/maciejkula/wyrm"
readme = "readme.md"

[badges]
travis-ci = { repository = "maciejkula/wyrm", branch = "master" }

[features]
fast-math = []

[dependencies]
ndarray = { version = "0.11.0", features = ["serde-1"] }
rand = { version = "0.5.0", features = ["serde1"] }
smallvec = { version = "0.5.0", features = ["serde"] }
itertools = "0.7.3"
rayon = "1.0.0"
serde = { version = "1.0.0", features = ["rc"] }
serde_derive = "1.0.0"
hibitset = "0.5.0"

[dev-dependencies]
ndarray = { version = "0.11.0", features = ["blas", "serde-1"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["static"] }
criterion = "0.2.3"

[[bench]]
name = "benchmark"
harness = false

[profile.bench]
lto = true
debug = true

[profile.release]
lto = true
